name: EMMCOMMprova
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - torch
      - numpy
      - scipy
      - scikit-learn
      - matplotlib
      - gymnasium
      - ucimlrepo
      - pytest
      - tensorboard
      - stable_baselines3
